### ISSUE TITLE
bug: can't push LFS object to public fork

### ISSUE THREAD

**Issue by benmiller314** [benmiller314/cdm2019fall#9]
Several students wrote to me today to say they'd gotten an error message: they weren't allowed to push their GIMP .xcf files to GitHub. 

![error message](https://user-images.githubusercontent.com/3182049/66578675-851e3480-eb49-11e9-8fcb-d57ec77f28c3.png)

Problem! I'd set up the .gitattributes file to designate .xcf files as [Git-LFS](https://git-lfs.github.com) objects, and now they were blocked, because public forks don't allow LFS objects to be pushed.

But this is also confusing, because we'd been able to use Git-LFS just fine with Audacity. What's up?

**Comment by benmiller314** [comment]
It [turns out](https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273) that it's not a blanket prohibition on Git-LFS objects in general; it's just that the owner of the repository has to signal that they want LFS objects first, by including at least one LFS object themselves.

For the soundscape project, I'd included .mp3 files in my .gitattributes setup for LFS, and I'd included the mystery-sound.mp3 file, so everything worked fine.

So I went ahead and added a new .xcf file to the original ("upstream") repository, so hopefully this will just start working again now.

**Comment by benmiller314** [comment]
However, if it doesn't work, you may need to pull the changes from that upstream branch. If you're comfortable with command line, there are good instructions on how to do that here: [help.github.com/en/articles/merging-an-upstream-repository-into-your-fork](https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork).

But if you're not sure what those instructions are doing, and you'd rather not mess around in command line without that understanding, there's also a way to do it with GitHub Desktop. I couldn't find a good visual walkthrough of that process, so I'm making one here.

# Merge from Upstream Branch in GitHub Desktop

## Open your repo in GitHub Desktop
![01-find-your-repo](https://user-images.githubusercontent.com/3182049/66580349-43db5400-eb4c-11e9-8150-e6023e30cf07.png)

## Pull down the branches menu

![02-pull-down-branch-menu](https://user-images.githubusercontent.com/3182049/66580468-75541f80-eb4c-11e9-94cb-c569d6a9155d.png)

If you see a branch called "upstream/master," you know you're in a forked repo. Don't click on the upstream here, though: you want to be on the destination branch, which is probably just called "master."

![03-confirm-upstream-exists](https://user-images.githubusercontent.com/3182049/66581265-d2040a00-eb4d-11e9-8914-d7b750980c0e.png)


## Start the merge.
Once you know you're in the right place, click on the button at the bottom to "choose a branch to merge into master (or whatever your local branch is called).

![04-choose-branch-to-merge](https://user-images.githubusercontent.com/3182049/66580629-b9472480-eb4c-11e9-9d69-7ffd7dd0ad94.png)

## Select the upstream branch as the merge source

On the next screen, you can now select the upstream/master to merge into master.

![05-merge-upstream-into-local](https://user-images.githubusercontent.com/3182049/66580826-01664700-eb4d-11e9-8b08-a010fc8f28d0.png)

If there are no conflicts, you'll get right back to your GitHub Desktop homescreen – perhaps with a prompt to push the changes you just merged in.

![06-successful-merge](https://user-images.githubusercontent.com/3182049/66580897-2064d900-eb4d-11e9-8628-7f29b319146d.png)

## Uh oh! It won't let me merge!

If the changes from the repo you forked (the "upstream") conflict with the changes you've made to your new repo – e.g. if you've written your own README.md file, and the upstream would revert your edits – you'll have to resolve a merge conflict. You'll first encounter this warning at the merge stage:

![05-merge-upstream-into-local--with-error](https://user-images.githubusercontent.com/3182049/66581286-dcbe9f00-eb4d-11e9-8b72-21501d8dc084.png)

GitHub Desktop will then helpfully offer to open your preferred text editor to fix the merge conflict.

![07-resolve-conflict-warning](https://user-images.githubusercontent.com/3182049/66581426-0ed00100-eb4e-11e9-9017-6e1c01e64583.png)

### Option one: conflict avoidance

Depending on the filetype where the error occurs, it may be easier just to 

1. cancel the merge
2. temporarily remove your new-and-improved local version from your repository
3. try the merge again using the steps above, without the conflict this time 
4. return the new-and-improved file to the repository
5. commit that change and carry on with your life.

### Option two: fix it with help

But if the change really is in a text-based file, it might be easy enough to pick the versions you want – even going line-by-line. For this, I highly recommend the text editor [Atom](https://atom.io). One of its neat features is that it has git merge resolution built in. It will highlight the local version (as "our changes") and the version from the merge (as "their changes"), and all you have to do is click a single "Use me" button at the top of the highlighting and Atom takes care of the rest.

![08-resolve-merge-with-atom](https://user-images.githubusercontent.com/3182049/66581893-e4327800-eb4e-11e9-8050-bfcfb32dded2.png)

At that point, you can head back to GitHub Desktop to carry on with the merge:

![09-conflicts-resolved](https://user-images.githubusercontent.com/3182049/66581937-f7ddde80-eb4e-11e9-9d26-e6df948ae957.png)

## Last step: push
That should bring you back to the home screen, where GitHub Desktop will probably suggest (as in the original, merge-conflict-free scenario) that you push your changes.

And you can get on with your actual editing!

**Comment by JasmineCT** [comment]
@benmiller314 
I had the same issue with the pop up of:
<img width="572" alt="Screen Shot 2020-10-28 at 1 50 33 PM" src="https://user-images.githubusercontent.com/31959259/97476952-6a218c80-1925-11eb-92c7-b934e3de4c3e.png">
 I followed the solution of merging upstream/master to the master, and it was successful to merge but I still get the pop up of unable to push.

**Comment by benmiller314** [comment]
@JasmineCT Do you think it might be the same problem of git-lfs being enabled, but not having any files that use git-lfs in the upstream repository you forked? You might need to contact the owner of that repo, whether on their issue queue or with a pull request.

**Comment by JasmineCT** [comment]
@benmiller314 it could be that issue. It's actually my repository, but I never created an upstream branch. I'm not sure where it cam from.

**Comment by benmiller314** [comment]
Weird. Do you remember forking a repository, possibly even your own? That's
the only way to have an "upstream" and "downstream," as far as I know.

You should be able to see the full fork network (including the upstream /
root) when you go to https://github.com/JasmineCT/portfolio/network/members
(or substitute the actual repo URL for the part before /network/members).
